root: true
extends:
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - prettier
  - plugin:svelte/recommended
  - plugin:svelte/prettier
  - prettier
globals:
  NodeJS: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  sourceType: module
  ecmaVersion: 2020
  project: './tsconfig.eslint.json'
  extraFileExtensions:
    - '.svelte'
env:
  browser: true
  es2017: true
  node: true
overrides:
  - files:
      - '*.svelte'
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
rules:
  '@typescript-eslint/class-methods-use-this': error
  '@typescript-eslint/consistent-type-exports': error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/default-param-last': error
  '@typescript-eslint/explicit-member-accessibility':
    - error
    - accessibility: no-public
  '@typescript-eslint/method-signature-style': error
  '@typescript-eslint/no-import-type-side-effects': error
  '@typescript-eslint/no-unnecessary-qualifier': error
  '@typescript-eslint/no-useless-empty-export': error
  '@typescript-eslint/prefer-nullish-coalescing':
    - error
    - ignorePrimitives: true
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-regexp-exec': error
  '@typescript-eslint/promise-function-async':
    - error
    - checkArrowFunctions: false
  '@typescript-eslint/require-array-sort-compare': error
  '@typescript-eslint/return-await': error
  '@typescript-eslint/sort-type-constituents': error
  '@typescript-eslint/switch-exhaustiveness-check': error

  func-style:
    - error
    - declaration

  # SvelteKit uses that for returning errors in routes
  '@typescript-eslint/no-throw-literal': 'off'

  # Receiving markdown from the API
  svelte/no-at-html-tags: 'off'
