overrides:
  - files: '*.svelte'
    options:
      parser: svelte
pluginSearchDirs:
  - '.'
plugins:
  - prettier-plugin-svelte
printWidth: 100
semi: false
singleQuote: true
trailingComma: all
useTabs: true
