name: Docker

on:
  push:
    tags: v*

jobs:
  docker_push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    if: ${{ github.actor != 'nektos/act' }}

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            natoboram/leanish
            ghcr.io/${{ github.repository }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            BUILD_BASE=
