name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_pages:
    runs-on: ubuntu-latest

    if: github.actor != 'nektos/act'

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build:csr
        env:
          BUILD_BASE: /Leanish
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy_pages:
    needs: build_pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
