name: Node.js Patch

on: workflow_dispatch

jobs:
  patch:
    runs-on: ubuntu-latest

    if: github.actor != 'nektos/act'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ssh-key: '${{ secrets.SIGNING_KEY_PRIVATE }}'
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - id: patch
        run: |
          echo "VERSION=$(pnpm version patch --no-git-tag-version)" >> "$GITHUB_OUTPUT"
          git add .

      - id: commit
        uses: qoomon/actions--create-commit@v1
        with:
          message: 🔖 ${{ steps.patch.outputs.VERSION }}

      - run: |
          git push
          gh release create "$VERSION" --generate-notes --target "$COMMIT" --title "$VERSION"
        env:
          COMMIT: ${{ steps.commit.outputs.commit }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.patch.outputs.VERSION }}
